
ENV PHPREDIS_VERSION=2.2.7
RUN cd /usr/src/php/ext \
    && curl -q https://codeload.github.com/phpredis/phpredis/tar.gz/$PHPREDIS_VERSION | tar -xz \
    && docker-php-ext-install phpredis-$PHPREDIS_VERSION
ENV REDIS_URL tcp://172.16.60.15:6379
RUN echo "session.save_handler = redis" > $PHP_INI_DIR/conf.d/redis-session.ini && \
    echo 'session.save_path = "${REDIS_URL}"' >> $PHP_INI_DIR/conf.d/redis-session.ini

