FROM ubuntu:16.04

RUN apt-get -y update && \
    apt-get -y install software-properties-common && \
    add-apt-repository ppa:ethereum/ethereum && \
    apt-get -y update && \
    apt-get -y install ethminer

